"""
Scientific Hypothesis Generation Workflow
==========================================
Fixed 4-turn pipeline – each turn is an independent trajectory record:

  Turn 0  [RETRIEVER]  query + up-to-5 paper summaries  →  ~100-word synthesis
  Turn 1  [GENERATOR]  query + retriever synthesis       →  question asking for more context
  Turn 2  [RETRIEVER]  generator question + same papers  →  focused follow-up (~100 words)
  Turn 3  [GENERATOR]  query + both retriever outputs    →  numbered hypothesis list

Each turn receives only its own fresh prompt; previous turns' outputs are
injected as plain text (thinking tokens stripped) rather than raw token IDs.
The MARTI framework tokenises each ``agent_input`` / ``agent_output`` pair
independently when constructing experiences.

Rewards
-------
  Retriever (turns 0 & 2) : gaussian centred at 100 words on content output
  Generator turn 1        : 1.0 if content output contains '?', else 0.0
  Generator turn 3        : format score (numbered items) + count score (peak at 3)

Data contract
-------------
  prompt   – raw user query string
  label    – ground-truth hypothesis (for logging; not used in reward)
  metadata – dict with key "papers": list of {"id", "title", "summary"} dicts

Debug logging
-------------
  Set DEBUG = True to write one JSON file per trajectory into the directory
  specified by kwargs["debug_dir"] (default: "./workflow_debug_logs").

  Each file is named:
      <debug_dir>/traj_<timestamp_ms>_<uuid4_short>.json

  Files are written atomically (temp file + rename) so concurrent async
  workflow calls never produce corrupted output.  The file contains:

      prompt_id       – prompt index within the current rollout batch (from MARTI)
      prompt          – original research query
      label           – ground-truth hypothesis
      total_reward    – sum of all 4 per-turn rewards
      elapsed_s       – wall-clock seconds for the full workflow call
      turns           – list of 4 dicts, one per turn:
          turn_id         – 0..3
          role            – "retriever" or "generator"
          input           – fresh ChatML prompt string fed to the model
          output          – raw text generated by the model
          output_content  – output with <think>…</think> stripped
          reward          – per-turn reward value
"""

import json
import os
import re
import time
import uuid
from typing import Any, Dict, List, Optional

from marti.utils.logging_utils import init_logger
from src.grpo.grpo_train.agents import AgentPrompts
from src.grpo.grpo_train.rewards import (
    retriever_word_count_reward,
    generator_request_format_reward,
    generator_hypothesis_reward,
)


logger = init_logger(__name__)
logger.setLevel("WARN")

# ──────────────────────────────────────────────────────────────────────────────
# Debug flag — flip to True to enable per-trajectory JSON logging
# ──────────────────────────────────────────────────────────────────────────────

DEBUG: bool = True

# ──────────────────────────────────────────────────────────────────────────────
# Prompt helpers
# ──────────────────────────────────────────────────────────────────────────────


def _fmt(role: str, content: str) -> str:
    """Format a single ChatML turn."""
    return f"<|im_start|>{role}\n{content}\n<|im_end|>\n"


def _build_prompt(system: str, user: str) -> str:
    """Full ChatML prompt ready for generation (ends at <|im_start|>assistant)."""
    return _fmt("system", system) + _fmt("user", user) + "<|im_start|>assistant\n"


# ──────────────────────────────────────────────────────────────────────────────
# Thinking-token helper
# ──────────────────────────────────────────────────────────────────────────────


def _strip_thinking(text: str) -> str:
    """Remove <think>...</think> blocks from model output.

    Qwen3 reasoning models wrap their internal chain-of-thought in
    ``<think>\\n...\\n</think>`` tags.  When the raw output of one agent is
    injected into the next agent's prompt we want to pass only the final
    answer, not the reasoning trace, so the context stays concise and the
    receiving agent is not confused by spurious thinking tokens.

    If no closing ``</think>`` tag is found the full text is returned
    unchanged (graceful degradation for non-reasoning models or empty
    thinking blocks).
    """
    stripped = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    return stripped.strip()


# ──────────────────────────────────────────────────────────────────────────────
# Paper context helpers
# ──────────────────────────────────────────────────────────────────────────────


def _format_papers(papers: List[Dict[str, str]], max_papers: int = 8) -> str:
    """Render a list of paper dicts into a readable block."""
    selected = papers[:max_papers]
    lines = []
    for i, p in enumerate(selected, 1):
        title = p.get("title", "Unknown title")
        summary = p.get("summary", p.get("abstract", "No summary available."))
        lines.append(f"[Paper {i}] {title}\n{summary.strip()}")
    return "\n\n".join(lines)


# ──────────────────────────────────────────────────────────────────────────────
# Debug helper
# ──────────────────────────────────────────────────────────────────────────────


def _write_debug_log(
    debug_dir: str,
    prompt_id: int,
    prompt: str,
    label: str,
    total_reward: float,
    elapsed_s: float,
    turns: List[Dict[str, Any]],
) -> None:
    """Write a single trajectory debug JSON file.

    Uses a millisecond timestamp + short UUID in the filename so concurrent
    async workflow calls never collide.  Writes to a temp file then renames
    atomically so a partial file is never visible to readers.
    """
    os.makedirs(debug_dir, exist_ok=True)
    ts_ms = int(time.time() * 1000)
    uid = uuid.uuid4().hex[:8]
    filename = f"traj_{ts_ms}_{uid}.json"
    path = os.path.join(debug_dir, filename)
    tmp_path = path + ".tmp"
    payload = {
        "prompt_id": prompt_id,
        "prompt": prompt,
        "label": label,
        "total_reward": total_reward,
        "elapsed_s": elapsed_s,
        "turns": turns,
    }
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    os.replace(tmp_path, path)
    logger.warning(f"[DEBUG] trajectory log written → {path}")


# ──────────────────────────────────────────────────────────────────────────────
# Main workflow
# ──────────────────────────────────────────────────────────────────────────────


async def workflow(
    prompt: str,
    label: str,
    agents: List[Dict[str, Any]],
    tool_manager=None,
    task: str = "scientific_hypothesis",
    metadata: Optional[Dict] = None,
    **kwargs,
) -> Dict[str, Any]:
    """
    Fixed 4-turn scientific hypothesis generation pipeline.

    Each turn is an independent generation call with its own fresh prompt.
    Prior turns' outputs are passed as plain text (thinking stripped) inside
    the next turn's user message.  The MARTI framework receives a list of
    per-turn trajectory dicts and tokenises them independently.

    Parameters
    ----------
    prompt   : The user research query.
    label    : Ground-truth hypothesis (for logging; not used in reward).
    agents   : List with at least one agent dict containing 'llm', 'tokenizer',
               'sampling_params'.  A single model plays both roles.
    metadata : Must include key 'papers': list of dicts with 'id', 'title',
               'summary' fields, pre-loaded from 11_neo4j_papers.csv.
    """
    t_start = time.time()

    # ── agent setup ──────────────────────────────────────────────────────────
    agent = agents[0]
    llm = agent["llm"]
    tokenizer = agent["tokenizer"]
    sp = agent["sampling_params"]
    agent_name: str = agent.get("agent_id", "shared_agent")

    # Ensure model stops cleanly at the end of each assistant turn
    stop_tokens = ["<|im_end|>", "<|endoftext|>"]
    if hasattr(sp, "stop"):
        sp.stop = stop_tokens
    elif isinstance(sp, dict):
        sp["stop"] = stop_tokens

    metadata = json.loads(json.loads(metadata))
    papers: List[Dict[str, str]] = (metadata or {}).get("papers", [])
    paper_block = _format_papers(papers, max_papers=5)
    logger.warning(f"len of paper block: {len(paper_block)} chars")

    # ── debug config ─────────────────────────────────────────────────────────
    debug_dir: str = kwargs.get("debug_dir", "./workflow_debug_logs")
    prompt_id: int = kwargs.get("prompt_id", 0)
    debug_turns: List[Dict[str, Any]] = []

    # ── per-turn trajectory accumulator ──────────────────────────────────────
    trajectory: List[Dict[str, Any]] = []
    total_reward = 0.0

    # ──────────────────────────────────────────────────────────────────────────
    # Turn 0 – RETRIEVER: synthesise paper summaries into a concise message
    # ──────────────────────────────────────────────────────────────────────────
    turn0_prompt = _build_prompt(
        system=AgentPrompts.retriever_system(),
        user=f"Research query:\n{prompt}\n\nAvailable papers:\n{paper_block}",
    )
    resp0 = await llm.generate_async.remote(
        prompt_ids=tokenizer(
            turn0_prompt, add_special_tokens=False, return_tensors="pt"
        )["input_ids"][0].tolist(),
        sampling_params=sp,
    )
    out0: str = resp0.outputs[0].text
    out0_content = _strip_thinking(out0)
    r0 = retriever_word_count_reward(out0_content)
    total_reward += r0
    retriever_msg_1 = out0_content  # passed as plain text to generator

    trajectory.append(
        {
            "turn_id": 0,
            "agent_index": 0,
            "agent_name": agent_name,
            "agent_role": "retriever",
            "agent_input": turn0_prompt,
            "agent_output": out0,
            "agent_reward": r0,
            "metadata": {},
        }
    )
    if DEBUG:
        debug_turns.append(
            {
                "turn_id": 0,
                "role": "retriever",
                "input": turn0_prompt,
                "output": out0,
                "output_content": out0_content,
                "reward": r0,
            }
        )

    # ──────────────────────────────────────────────────────────────────────────
    # Turn 1 – GENERATOR: ask for additional context
    # ──────────────────────────────────────────────────────────────────────────
    turn1_prompt = _build_prompt(
        system=AgentPrompts.generator_ask_system(),
        user=f"Research query:\n{prompt}\n\nRetriever synthesis:\n{retriever_msg_1}",
    )
    resp1 = await llm.generate_async.remote(
        prompt_ids=tokenizer(
            turn1_prompt, add_special_tokens=False, return_tensors="pt"
        )["input_ids"][0].tolist(),
        sampling_params=sp,
    )
    out1: str = resp1.outputs[0].text
    out1_content = _strip_thinking(out1)
    r1 = generator_request_format_reward(out1_content)
    total_reward += r1
    gen_request = out1_content  # passed as plain text to retriever

    trajectory.append(
        {
            "turn_id": 1,
            "agent_index": 0,
            "agent_name": agent_name,
            "agent_role": "generator",
            "agent_input": turn1_prompt,
            "agent_output": out1,
            "agent_reward": r1,
            "metadata": {},
        }
    )
    if DEBUG:
        debug_turns.append(
            {
                "turn_id": 1,
                "role": "generator",
                "input": turn1_prompt,
                "output": out1,
                "output_content": out1_content,
                "reward": r1,
            }
        )

    # ──────────────────────────────────────────────────────────────────────────
    # Turn 2 – RETRIEVER: respond to generator's request with focused context
    # ──────────────────────────────────────────────────────────────────────────
    turn2_prompt = _build_prompt(
        system=AgentPrompts.retriever_system(),
        user=(
            f"The generator is asking:\n{gen_request}\n\n"
            f"Available papers (same pool):\n{paper_block}"
        ),
    )
    resp2 = await llm.generate_async.remote(
        prompt_ids=tokenizer(
            turn2_prompt, add_special_tokens=False, return_tensors="pt"
        )["input_ids"][0].tolist(),
        sampling_params=sp,
    )
    out2: str = resp2.outputs[0].text
    out2_content = _strip_thinking(out2)
    r2 = retriever_word_count_reward(out2_content)
    total_reward += r2
    retriever_msg_2 = out2_content  # passed as plain text to generator

    trajectory.append(
        {
            "turn_id": 2,
            "agent_index": 0,
            "agent_name": agent_name,
            "agent_role": "retriever",
            "agent_input": turn2_prompt,
            "agent_output": out2,
            "agent_reward": r2,
            "metadata": {},
        }
    )
    if DEBUG:
        debug_turns.append(
            {
                "turn_id": 2,
                "role": "retriever",
                "input": turn2_prompt,
                "output": out2,
                "output_content": out2_content,
                "reward": r2,
            }
        )

    # ──────────────────────────────────────────────────────────────────────────
    # Turn 3 – GENERATOR: produce the final hypothesis list
    # ──────────────────────────────────────────────────────────────────────────
    turn3_prompt = _build_prompt(
        system=AgentPrompts.generator_hypothesize_system(),
        user=(
            f"Research query:\n{prompt}\n\n"
            f"Retriever synthesis:\n{retriever_msg_1}\n\n"
            f"Additional retriever context:\n{retriever_msg_2}"
        ),
    )
    resp3 = await llm.generate_async.remote(
        prompt_ids=tokenizer(
            turn3_prompt, add_special_tokens=False, return_tensors="pt"
        )["input_ids"][0].tolist(),
        sampling_params=sp,
    )
    out3: str = resp3.outputs[0].text
    out3_content = _strip_thinking(out3)
    r3 = generator_hypothesis_reward(out3_content)
    total_reward += r3

    trajectory.append(
        {
            "turn_id": 3,
            "agent_index": 0,
            "agent_name": agent_name,
            "agent_role": "generator",
            "agent_input": turn3_prompt,
            "agent_output": out3,
            "agent_reward": r3,
            "metadata": {"label": label},
        }
    )
    if DEBUG:
        debug_turns.append(
            {
                "turn_id": 3,
                "role": "generator",
                "input": turn3_prompt,
                "output": out3,
                "output_content": out3_content,
                "reward": r3,
            }
        )

    elapsed = time.time() - t_start
    logger.warning(
        f"workflow done | turns=4 | reward={total_reward:.3f} | time={elapsed:.1f}s"
    )

    if DEBUG:
        _write_debug_log(
            debug_dir=debug_dir,
            prompt_id=prompt_id,
            prompt=prompt,
            label=label,
            total_reward=total_reward,
            elapsed_s=round(elapsed, 2),
            turns=debug_turns,
        )

    return {
        "prompt": prompt,
        "label": label,
        "trajectory": trajectory,
        "final_reward": total_reward,
    }
