"""Pipeline entry point for the hypothesis generation API.

Set PIPELINE_USE_MOCK=false (plus the appropriate API keys and DB connections)
to swap in the real pipeline.  Mock mode is the default and requires no
external services.

Chat continuation uses OpenAI-compatible function/tool calling so the LLM
can retrieve structured context about the session while composing replies.
Any endpoint compatible with the OpenAI Chat Completions API works:
  - OpenAI (set OPENAI_API_KEY)
  - vLLM   (set OPENAI_BASE_URL=http://host:port/v1  and OPENAI_API_KEY=dummy)
  - Ollama  (set OPENAI_BASE_URL=http://localhost:11434/v1)
  - Groq, Together AI, Cerebras, etc.

See INTEGRATION.md for full setup instructions.
"""

import json
import os
import sys
import time
from datetime import datetime, timezone
from uuid import uuid4

from api.config import get_settings
from api.mocks import mock_chat_reply, run_mock
from api.models import (
    ExplorationStats,
    HypothesisOut,
    ReasoningStep,
    SessionOut,
)
from api.tools import CHAT_TOOLS, execute_tool


def _build_system_prompt(session: SessionOut) -> str:
    lines = [
        "You are a scientific research assistant helping to develop a hypothesis "
        "generated by an AI pipeline.",
        "",
        f"## Research Question\n{session.question}",
        "",
        "## Generated Hypotheses",
    ]
    for h in session.hypotheses:
        lines += [
            f"\n### Hypothesis {h.id} — {h.headline}",
            f"Classification: {h.classification}",
            f"Statement: {h.statement}",
            f"Falsifiable prediction: {h.falsifiablePrediction}",
            f"Evidence drawn from: {', '.join(h.drawnFrom)}",
        ]

    if session.selectedId:
        selected = next((h for h in session.hypotheses if h.id == session.selectedId), None)
        lines += [
            "",
            f"## User's Selection",
            f"The user chose Hypothesis {session.selectedId}"
            + (f" — {selected.headline}" if selected else ""),
        ]
        if session.rationale:
            lines.append(f"Rationale: {session.rationale}")

    lines += [
        "",
        "## Knowledge Graph Context",
        f"Communities explored: {', '.join(session.exploration.communities)}",
        f"Nodes traversed: {session.exploration.nodesTraversed}",
        f"Relations: {session.exploration.relations}",
        "",
        "## Instructions",
        "- Help the user develop and extend their chosen hypothesis through rigorous scientific discussion.",
        "- Reference evidence from the knowledge graph when relevant.",
        "- Use the available tools when you need to retrieve additional context.",
        "- Suggest specific, falsifiable experiments where appropriate.",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Chat entry point
# ---------------------------------------------------------------------------


def generate_chat_reply(session: SessionOut, user_message: str) -> str:
    settings = get_settings()
    if settings.pipeline_use_mock:
        return mock_chat_reply(session, user_message)
    return _real_chat_reply(session, user_message, settings=settings)


def _real_chat_reply(session: SessionOut, user_message: str, settings=None) -> str:
    """Context-aware chat using OpenAI-compatible tool calling.

    Works with any OpenAI-compatible endpoint:
      - OpenAI:  set OPENAI_API_KEY
      - vLLM:    set OPENAI_BASE_URL=http://host:8000/v1  OPENAI_API_KEY=dummy
      - Ollama:  set OPENAI_BASE_URL=http://localhost:11434/v1

    Model is read from API settings.
    """
    from openai import OpenAI  # noqa: PLC0415

    settings = settings or get_settings()
    client = OpenAI(
        api_key=settings.openai_api_key,
        base_url=settings.openai_base_url,
    )

    messages: list[dict] = [{"role": "system", "content": _build_system_prompt(session)}]

    # Replay last 20 messages (10 turns) to stay within context limits
    for msg in session.messages[-20:]:
        messages.append({"role": msg.role, "content": msg.content})

    messages.append({"role": "user", "content": user_message})

    # Tool-calling loop (capped at 5 iterations to prevent runaway)
    last_content = ""
    for _ in range(5):
        response = client.chat.completions.create(
            model=settings.chat_model,
            messages=messages,
            tools=CHAT_TOOLS,
            tool_choice="auto",
        )
        choice = response.choices[0]
        last_content = choice.message.content or ""

        if choice.finish_reason == "stop" or not choice.message.tool_calls:
            return last_content

        # Append assistant turn with tool_calls
        messages.append(
            {
                "role": "assistant",
                "content": last_content,
                "tool_calls": [
                    {
                        "id": tc.id,
                        "type": "function",
                        "function": {"name": tc.function.name, "arguments": tc.function.arguments},
                    }
                    for tc in choice.message.tool_calls
                ],
            }
        )

        # Execute each tool and append results
        for tc in choice.message.tool_calls:
            try:
                args = json.loads(tc.function.arguments or "{}")
            except json.JSONDecodeError:
                args = {}
            result = execute_tool(tc.function.name, args, session)
            messages.append({"role": "tool", "tool_call_id": tc.id, "content": result})

    return last_content or "Context gathered. Please ask your follow-up question."


# ---------------------------------------------------------------------------
# Pipeline entry point
# ---------------------------------------------------------------------------


def run_pipeline(
    question: str,
    retriever_model_name: str,
    generator_model_name: str,
) -> SessionOut:
    settings = get_settings()
    if settings.pipeline_use_mock:
        return run_mock(question, retriever_model_name, generator_model_name)
    return _run_real(
        question,
        retriever_model_name,
        generator_model_name,
        settings=settings,
    )


# ---------------------------------------------------------------------------
# Real pipeline implementation
# ---------------------------------------------------------------------------


def _run_real(
    question: str,
    retriever_model_name: str,
    generator_model_name: str,
    settings=None,
) -> SessionOut:
    """Run the full pipeline with real models and knowledge graph.

    Requires API settings, API keys, and DB connections.
    See INTEGRATION.md for full setup instructions.
    """
    _ensure_src_on_path()

    from app.app import Pipeline  # noqa: PLC0415
    from app.explorer.neo4j_random_walk_explorer import Neo4jRandomWalkExplorer  # noqa: PLC0415
    from app.generator.openai_chat_generator import OpenAIChatGenerator  # noqa: PLC0415
    from app.retriever.openai_chat_retriever import OpenAIChatRetriever  # noqa: PLC0415

    settings = settings or get_settings()
    config = settings.pipeline_config()
    model_configs = {
        model_name: settings.get_model_config(model_name)
        for model_name in {retriever_model_name, generator_model_name}
    }

    explorer = Neo4jRandomWalkExplorer(config)
    search_explorer = _build_search(config)

    pipeline = Pipeline(
        search_explorer=search_explorer,
        explorer=explorer,
        retriever=OpenAIChatRetriever(model_configs=model_configs),
        generator=OpenAIChatGenerator(model_configs=model_configs),
        config=config,
    )

    t0 = time.monotonic()
    result = pipeline.run(
        question,
        retriever_model_name=retriever_model_name,
        generator_model_name=generator_model_name,
        retriever_kwargs=_completion_kwargs(config.get("retriever", {}), exclude={"type", "top_k"}),
        generator_kwargs=_completion_kwargs(config.get("generator", {}), exclude={"type"}),
    )
    elapsed = round(time.monotonic() - t0, 3)

    trace = [
        ReasoningStep(
            step="Pipeline",
            description="Full search → explorer → retriever → generator run",
            durationSec=elapsed,
            details=f"Model: {result.metadata.get('model', 'unknown')}",
        )
    ]

    return SessionOut(
        sessionId=str(uuid4()),
        question=question,
        retrieverModelName=retriever_model_name,
        generatorModelName=generator_model_name,
        createdAt=datetime.now(timezone.utc).isoformat(),
        exploration=ExplorationStats(durationSec=elapsed),
        hypotheses=_wrap_hypotheses(result.hypotheses),
        reasoningTrace=trace,
    )


def _build_search(config: dict):
    t = config.get("search", {}).get("type", "const")
    if t == "weaviate":
        from app.explorer.weaviate_search_explorer import WeaviateSearchExplorer  # noqa: PLC0415
        return WeaviateSearchExplorer(config)
    return _NullSearch()


def _completion_kwargs(config: dict, exclude: set[str]) -> dict:
    return {key: value for key, value in config.items() if key not in exclude}


class _NullSearch:
    def search(self, prompt: str) -> list[str]:  # noqa: ARG002
        return []


def _ensure_src_on_path() -> None:
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    src = os.path.join(root, "src")
    if src not in sys.path:
        sys.path.insert(0, src)


def _wrap_hypotheses(raw: list[str]) -> list[HypothesisOut]:
    ids = ["A", "B"]
    out: list[HypothesisOut] = []
    for i, text in enumerate(raw[:2]):
        headline = text.split(". ", 1)[0].strip()[:120]
        out.append(
            HypothesisOut(
                id=ids[i],  # type: ignore[arg-type]
                classification=f"Hypothesis {ids[i]}",
                headline=headline,
                statement=text,
                drawnFrom=[],
                falsifiablePrediction="",
            )
        )
    while len(out) < 2:
        idx = len(out)
        out.append(
            HypothesisOut(
                id=ids[idx],  # type: ignore[arg-type]
                classification=f"Hypothesis {ids[idx]}",
                headline="(not generated)",
                statement="",
                drawnFrom=[],
                falsifiablePrediction="",
            )
        )
    return out
