"""Pipeline entry point for the hypothesis generation API.

Set PIPELINE_USE_MOCK=false (plus the appropriate API keys and DB connections)
to swap in the real pipeline.  Mock mode is the default and requires no
external services.

Chat continuation uses OpenAI-compatible function/tool calling so the LLM
can retrieve structured context about the session while composing replies.
Any endpoint compatible with the OpenAI Chat Completions API works:
  - OpenAI (set OPENAI_API_KEY)
  - vLLM   (set OPENAI_BASE_URL=http://host:port/v1  and OPENAI_API_KEY=dummy)
  - Ollama  (set OPENAI_BASE_URL=http://localhost:11434/v1)
  - Groq, Together AI, Cerebras, etc.

See INTEGRATION.md for full setup instructions.
"""

import json
import os
import sys
import time
from datetime import datetime, timezone
from uuid import uuid4

from api.mocks import MOCK_KG, MOCK_TRACE, H_A, H_B, mock_chat_reply, run_mock
from api.models import (
    HypothesisOut,
    Message,
    ReasoningStep,
    SessionOut,
)
from api.tools import CHAT_TOOLS, execute_tool


def _build_system_prompt(session: SessionOut) -> str:
    lines = [
        "You are a scientific research assistant helping to develop a hypothesis "
        "generated by an AI pipeline.",
        "",
        f"## Research Question\n{session.question}",
        "",
        "## Generated Hypotheses",
    ]
    for h in session.hypotheses:
        lines += [
            f"\n### Hypothesis {h.id} — {h.headline}",
            f"Classification: {h.classification}",
            f"Statement: {h.statement}",
            f"Falsifiable prediction: {h.falsifiablePrediction}",
            f"Evidence drawn from: {', '.join(h.drawnFrom)}",
        ]

    if session.selectedId:
        selected = next((h for h in session.hypotheses if h.id == session.selectedId), None)
        lines += [
            "",
            f"## User's Selection",
            f"The user chose Hypothesis {session.selectedId}"
            + (f" — {selected.headline}" if selected else ""),
        ]
        if session.rationale:
            lines.append(f"Rationale: {session.rationale}")

    lines += [
        "",
        "## Knowledge Graph Context",
        f"Communities explored: {', '.join(session.exploration.communities)}",
        f"Nodes traversed: {session.exploration.nodesTraversed}",
        f"Relations: {session.exploration.relations}",
        "",
        "## Instructions",
        "- Help the user develop and extend their chosen hypothesis through rigorous scientific discussion.",
        "- Reference evidence from the knowledge graph when relevant.",
        "- Use the available tools when you need to retrieve additional context.",
        "- Suggest specific, falsifiable experiments where appropriate.",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Chat entry point
# ---------------------------------------------------------------------------


def generate_chat_reply(session: SessionOut, user_message: str) -> str:
    if os.getenv("PIPELINE_USE_MOCK", "true").lower() != "false":
        return mock_chat_reply(session, user_message)
    return _real_chat_reply(session, user_message)


def _real_chat_reply(session: SessionOut, user_message: str) -> str:
    """Context-aware chat using OpenAI-compatible tool calling.

    Works with any OpenAI-compatible endpoint:
      - OpenAI:  set OPENAI_API_KEY
      - vLLM:    set OPENAI_BASE_URL=http://host:8000/v1  OPENAI_API_KEY=dummy
      - Ollama:  set OPENAI_BASE_URL=http://localhost:11434/v1

    Model is read from CHAT_MODEL (default: gpt-4o-mini).
    """
    from openai import OpenAI  # noqa: PLC0415

    client = OpenAI(
        api_key=os.getenv("OPENAI_API_KEY", "dummy"),
        base_url=os.getenv("OPENAI_BASE_URL"),  # None → use OpenAI directly
    )
    model = os.getenv("CHAT_MODEL", os.getenv("OPENAI_MODEL", "gpt-4o-mini"))

    messages: list[dict] = [{"role": "system", "content": _build_system_prompt(session)}]

    # Replay last 20 messages (10 turns) to stay within context limits
    for msg in session.messages[-20:]:
        messages.append({"role": msg.role, "content": msg.content})

    messages.append({"role": "user", "content": user_message})

    # Tool-calling loop (capped at 5 iterations to prevent runaway)
    last_content = ""
    for _ in range(5):
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            tools=CHAT_TOOLS,
            tool_choice="auto",
        )
        choice = response.choices[0]
        last_content = choice.message.content or ""

        if choice.finish_reason == "stop" or not choice.message.tool_calls:
            return last_content

        # Append assistant turn with tool_calls
        messages.append(
            {
                "role": "assistant",
                "content": last_content,
                "tool_calls": [
                    {
                        "id": tc.id,
                        "type": "function",
                        "function": {"name": tc.function.name, "arguments": tc.function.arguments},
                    }
                    for tc in choice.message.tool_calls
                ],
            }
        )

        # Execute each tool and append results
        for tc in choice.message.tool_calls:
            try:
                args = json.loads(tc.function.arguments or "{}")
            except json.JSONDecodeError:
                args = {}
            result = execute_tool(tc.function.name, args, session)
            messages.append({"role": "tool", "tool_call_id": tc.id, "content": result})

    return last_content or "Context gathered. Please ask your follow-up question."


# ---------------------------------------------------------------------------
# Pipeline entry point
# ---------------------------------------------------------------------------


def run_pipeline(question: str) -> SessionOut:
    if os.getenv("PIPELINE_USE_MOCK", "true").lower() != "false":
        return run_mock(question)
    return _run_real(question)


# ---------------------------------------------------------------------------
# Real pipeline implementation
# ---------------------------------------------------------------------------


def _run_real(question: str) -> SessionOut:
    """Run the full pipeline with real models and knowledge graph.

    Requires: config/app/config.yaml, API keys, and DB connections.
    See INTEGRATION.md for full setup instructions.
    """
    _ensure_src_on_path()

    from app.app import App  # noqa: PLC0415
    from app.config import load_config  # noqa: PLC0415
    from app.retriever.api_llm_retriever import APILLMRetriever  # noqa: PLC0415
    from app.generator.api_llm_generator import APILLMGenerator  # noqa: PLC0415

    config = load_config("config/app/config.yaml")
    provider = config.get("api_client", {}).get("type", "openai")
    model = config.get("api_client", {}).get("model", "gpt-4o-mini")
    api_client = _build_api_client(provider, model)

    explorer = _build_explorer(config)
    search_explorer = _build_search(config)

    app = App(
        search_explorer=search_explorer,
        explorer=explorer,
        retriever=APILLMRetriever(api_client=api_client),
        generator=APILLMGenerator(api_client=api_client),
        config_path="config/app/config.yaml",
    )

    t0 = time.monotonic()
    result = app.run(question)
    elapsed = round(time.monotonic() - t0, 3)

    trace = [
        ReasoningStep(
            step="Pipeline",
            description="Full search → explorer → retriever → generator run",
            durationSec=elapsed,
            details=f"Model: {result.metadata.get('model', 'unknown')}",
        )
    ]

    return SessionOut(
        sessionId=str(uuid4()),
        question=question,
        createdAt=datetime.now(timezone.utc).isoformat(),
        exploration=ExplorationStats(durationSec=elapsed),
        hypotheses=_wrap_hypotheses(result.hypotheses),
        reasoningTrace=trace,
    )


def _build_api_client(provider: str, model: str):
    if provider in ("openai", "openai_compatible"):
        from app.api_client.openai_compatible_client import OpenAICompatibleClient  # noqa: PLC0415
        return OpenAICompatibleClient(model=model)
    if provider == "google":
        from app.api_client.google_client import GoogleAPIClient  # noqa: PLC0415
        return GoogleAPIClient(model=model)
    if provider == "cerebras":
        from app.api_client.cerebras_client import CerebrasAPIClient  # noqa: PLC0415
        return CerebrasAPIClient(model=model)
    raise ValueError(f"Unknown provider: {provider!r}")


def _build_explorer(config: dict):
    from app.explorer.const_explorer import ConstExplorer  # noqa: PLC0415

    t = config.get("explorer", {}).get("type", "const")
    if t == "neo4j_bfs":
        from app.explorer.neo4j_bfs_explorer import Neo4jBFSExplorer  # noqa: PLC0415
        return Neo4jBFSExplorer(config)
    if t == "neo4j_pagerank":
        from app.explorer.neo4j_pagerank_explorer import Neo4jPageRankExplorer  # noqa: PLC0415
        return Neo4jPageRankExplorer(config)
    if t == "neo4j_random_walk":
        from app.explorer.neo4j_random_walk_explorer import Neo4jRandomWalkExplorer  # noqa: PLC0415
        return Neo4jRandomWalkExplorer(config)
    if t == "agentic":
        from app.explorer.agentic_explorer import AgenticExplorer  # noqa: PLC0415
        return AgenticExplorer(config)
    return ConstExplorer()


def _build_search(config: dict):
    t = config.get("search", {}).get("type", "const")
    if t == "weaviate":
        from app.explorer.weaviate_search_explorer import WeaviateSearchExplorer  # noqa: PLC0415
        return WeaviateSearchExplorer(config)
    return _NullSearch()


class _NullSearch:
    def search(self, prompt: str) -> list[str]:  # noqa: ARG002
        return []


def _ensure_src_on_path() -> None:
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    src = os.path.join(root, "src")
    if src not in sys.path:
        sys.path.insert(0, src)


def _wrap_hypotheses(raw: list[str]) -> list[HypothesisOut]:
    ids = ["A", "B"]
    out: list[HypothesisOut] = []
    for i, text in enumerate(raw[:2]):
        headline = text.split(". ", 1)[0].strip()[:120]
        out.append(
            HypothesisOut(
                id=ids[i],  # type: ignore[arg-type]
                classification=f"Hypothesis {ids[i]}",
                headline=headline,
                statement=text,
                drawnFrom=[],
                falsifiablePrediction="",
            )
        )
    while len(out) < 2:
        idx = len(out)
        out.append(
            HypothesisOut(
                id=ids[idx],  # type: ignore[arg-type]
                classification=f"Hypothesis {ids[idx]}",
                headline="(not generated)",
                statement="",
                drawnFrom=[],
                falsifiablePrediction="",
            )
        )
    return out
