"""Pipeline entry point for the hypothesis generation API.

Set PIPELINE_USE_MOCK=false (plus the appropriate API keys and DB connections)
to swap in the real pipeline.  Mock mode is the default and requires no
external services.

Chat continuation uses OpenAI-compatible function/tool calling so the LLM
can retrieve structured context about the session while composing replies.
Any endpoint compatible with the OpenAI Chat Completions API works:
  - OpenAI (set OPENAI_API_KEY)
  - vLLM   (set OPENAI_BASE_URL=http://host:port/v1  and OPENAI_API_KEY=dummy)
  - Ollama  (set OPENAI_BASE_URL=http://localhost:11434/v1)
  - Groq, Together AI, Cerebras, etc.

See INTEGRATION.md for full setup instructions.
"""

import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

_PERSONAS_PATH = Path(__file__).resolve().parents[2] / "personas" / "personas_all.json"


def _load_persona(persona_id: str | None) -> dict | None:
    if not persona_id:
        return None
    with open(_PERSONAS_PATH) as f:
        personas = json.load(f)
    return next((p for p in personas if p["persona_id"] == persona_id), None)

from api.config import get_settings
from api.mocks import mock_chat_reply, run_mock
from api.models import (
    ExplorationStats,
    HypothesisOut,
    KGEdge,
    KGNode,
    KnowledgeGraph,
    ReasoningStep,
    SessionOut,
)
from api.tools import CHAT_TOOLS, execute_tool


def _build_system_prompt(session: SessionOut) -> str:
    lines = [
        "You are a scientific research assistant helping to develop a hypothesis "
        "generated by an AI pipeline.",
        "",
        f"## Research Question\n{session.question}",
        "",
    ]

    if session.personaId:
        persona = _load_persona(session.personaId)
        if persona:
            lines += [
                "## Active Persona",
                f"The hypotheses were generated under the **{persona['display_name']}** persona.",
                f"Core philosophy: {persona['core_philosophy']}",
                f"Communication style: {persona['communication_style']}",
                "Continue the conversation in this persona's voice and analytical frame.",
                "",
            ]

    lines += [
        "## Generated Hypotheses",
    ]
    for h in session.hypotheses:
        lines += [
            f"\n### Hypothesis {h.id} — {h.headline}",
            f"Classification: {h.classification}",
            f"Statement: {h.statement}",
            f"Falsifiable prediction: {h.falsifiablePrediction}",
            f"Evidence drawn from: {', '.join(h.drawnFrom)}",
        ]

    if session.selectedId:
        selected = next((h for h in session.hypotheses if h.id == session.selectedId), None)
        lines += [
            "",
            f"## User's Selection",
            f"The user chose Hypothesis {session.selectedId}"
            + (f" — {selected.headline}" if selected else ""),
        ]
        if session.rationale:
            lines.append(f"Rationale: {session.rationale}")

    lines += [
        "",
        "## Knowledge Graph Context",
        f"Communities explored: {', '.join(session.exploration.communities)}",
        f"Nodes traversed: {session.exploration.nodesTraversed}",
        f"Relations: {session.exploration.relations}",
        "",
        "## Instructions",
        "- Help the user develop and extend their chosen hypothesis through rigorous scientific discussion.",
        "- Reference evidence from the knowledge graph when relevant.",
        "- Use the available tools when you need to retrieve additional context.",
        "- Suggest specific, falsifiable experiments where appropriate.",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Chat entry point
# ---------------------------------------------------------------------------


def generate_chat_reply(session: SessionOut, user_message: str) -> str:
    settings = get_settings()
    if settings.pipeline_use_mock:
        return mock_chat_reply(session, user_message)
    return _real_chat_reply(session, user_message, settings=settings)


def _real_chat_reply(session: SessionOut, user_message: str, settings=None) -> str:
    """Stateless chat continuation using the session's generator model endpoint.

    Passes the full conversation history (system prompt + prior turns + new
    message) in a single call — no tool calling, which requires special vLLM
    server flags that may not be present.
    """
    from openai import OpenAI  # noqa: PLC0415

    settings = settings or get_settings()

    # Use the session's generator model endpoint for continuations.
    try:
        model_cfg = settings.get_model_config(session.generatorModelName)
        chat_model = model_cfg["api_model"]
        api_key = model_cfg.get("api_key", "dummy")
        base_url = model_cfg.get("base_url")
    except KeyError:
        chat_model = settings.chat_model
        api_key = settings.openai_api_key
        base_url = settings.openai_base_url

    client = OpenAI(api_key=api_key, base_url=base_url)

    messages: list[dict] = [{"role": "system", "content": _build_system_prompt(session)}]

    # Replay last 20 messages (10 turns) to stay within context limits.
    for msg in session.messages[-20:]:
        messages.append({"role": msg.role, "content": msg.content})

    messages.append({"role": "user", "content": user_message})

    response = client.chat.completions.create(model=chat_model, messages=messages)
    return response.choices[0].message.content or ""


# ---------------------------------------------------------------------------
# Pipeline entry point
# ---------------------------------------------------------------------------


def run_pipeline(
    question: str,
    retriever_model_name: str,
    generator_model_name: str,
    persona_id: str | None = None,
) -> SessionOut:
    settings = get_settings()
    if settings.pipeline_use_mock:
        return run_mock(question, retriever_model_name, generator_model_name, persona_id=persona_id)
    return _run_real(
        question,
        retriever_model_name,
        generator_model_name,
        persona_id=persona_id,
        settings=settings,
    )


# ---------------------------------------------------------------------------
# Real pipeline implementation
# ---------------------------------------------------------------------------


def _run_real(
    question: str,
    retriever_model_name: str,
    generator_model_name: str,
    persona_id: str | None = None,
    settings=None,
) -> SessionOut:
    """Run the full pipeline with real models and knowledge graph.

    Requires API settings, API keys, and DB connections.
    See INTEGRATION.md for full setup instructions.
    """
    _ensure_src_on_path()

    from app.app import Pipeline  # noqa: PLC0415
    from app.explorer.api_weaviate_search_explorer import ApiWeaviateSearchExplorer  # noqa: PLC0415
    from app.explorer.neo4j_random_walk_explorer import Neo4jRandomWalkExplorer  # noqa: PLC0415
    from app.generator.openai_chat_generator import OpenAIChatGenerator  # noqa: PLC0415
    from app.retriever.openai_chat_retriever import OpenAIChatRetriever  # noqa: PLC0415

    settings = settings or get_settings()
    config = settings.pipeline_config()
    model_configs = {
        model_name: settings.get_model_config(model_name)
        for model_name in {retriever_model_name, generator_model_name}
    }

    explorer = Neo4jRandomWalkExplorer(config)
    search_explorer = ApiWeaviateSearchExplorer(config)

    pipeline = Pipeline(
        search_explorer=search_explorer,
        explorer=explorer,
        retriever=OpenAIChatRetriever(model_configs=model_configs),
        generator=OpenAIChatGenerator(model_configs=model_configs),
        config=config,
    )

    persona = _load_persona(persona_id)

    # Route to the dedicated persona model when one is configured.
    effective_generator = generator_model_name
    if persona and settings.persona_model and settings.persona_model in settings.model_configs:
        effective_generator = settings.persona_model
        model_configs[effective_generator] = settings.get_model_config(effective_generator)

    generator_kwargs = _completion_kwargs(config.get("generator", {}), exclude={"type"})
    if persona:
        generator_kwargs["persona"] = persona

    t0 = time.monotonic()
    result = pipeline.run(
        question,
        retriever_model_name=retriever_model_name,
        generator_model_name=effective_generator,
        retriever_kwargs=_completion_kwargs(config.get("retriever", {}), exclude={"type", "top_k"}),
        generator_kwargs=generator_kwargs,
    )
    elapsed = round(time.monotonic() - t0, 3)

    explorer_meta = result.metadata.get("explorer", {})
    kg = _build_knowledge_graph(explorer_meta, question)
    papers = explorer_meta.get("papers", [])
    starting = explorer_meta.get("starting_papers", [])

    generator_details = f"Model: {result.metadata.get('model', effective_generator)}"
    if result.reasoning:
        generator_details = result.reasoning

    trace = [
        ReasoningStep(
            step="Pipeline",
            description="Full search → explorer → retriever → generator run",
            durationSec=elapsed,
            details=generator_details,
        )
    ]

    return SessionOut(
        sessionId=str(uuid4()),
        question=question,
        retrieverModelName=retriever_model_name,
        generatorModelName=effective_generator,
        personaId=persona_id,
        createdAt=datetime.now(timezone.utc).isoformat(),
        exploration=ExplorationStats(
            nodesTraversed=len(papers),
            relations=len(kg.edges),
            sourcePapers=len(starting),
            durationSec=elapsed,
        ),
        hypotheses=_wrap_hypotheses(result.hypotheses, reasoning=result.reasoning),
        reasoningTrace=trace,
        knowledgeGraph=kg if kg.nodes else None,
    )


def _build_knowledge_graph(explorer_meta: dict, question: str) -> KnowledgeGraph:
    """Convert Neo4j explorer metadata into a KnowledgeGraph for the frontend."""
    papers: list[dict] = explorer_meta.get("papers", [])
    nodes: list[KGNode] = [KGNode(id="query", label=question[:80], type="query")]
    edges: list[KGEdge] = []
    added: set[str] = {"query"}

    # Sort by level so source papers exist before their children are linked.
    for paper in sorted(papers, key=lambda p: p.get("level", 0)):
        pid = paper.get("id", "")
        if not pid or pid in added:
            continue
        added.add(pid)
        nodes.append(KGNode(
            id=pid,
            label=(paper.get("title") or pid)[:80],
            type="paper",
            paperId=pid,
            abstract=paper.get("abstract") or None,
            summary=paper.get("summary") or None,
        ))
        level = paper.get("level", 0)
        source = paper.get("source_id", "query") if level > 0 else "query"
        if source not in added:
            source = "query"
        edges.append(KGEdge(source=source, target=pid, relation="explored"))

    return KnowledgeGraph(nodes=nodes, edges=edges)


def _completion_kwargs(config: dict, exclude: set[str]) -> dict:
    return {key: value for key, value in config.items() if key not in exclude}


def _ensure_src_on_path() -> None:
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    src = os.path.join(root, "src")
    if src not in sys.path:
        sys.path.insert(0, src)


def _wrap_hypotheses(raw: list[str], reasoning: str = "") -> list[HypothesisOut]:
    ids = ["A", "B"]
    out: list[HypothesisOut] = []
    for i, text in enumerate(raw[:2]):
        headline = text.split(". ", 1)[0].strip()[:120]
        out.append(
            HypothesisOut(
                id=ids[i],  # type: ignore[arg-type]
                classification=f"Hypothesis {ids[i]}",
                headline=headline,
                statement=text,
                drawnFrom=[],
                falsifiablePrediction="",
                reasoning=reasoning or None,
            )
        )
    while len(out) < 2:
        idx = len(out)
        out.append(
            HypothesisOut(
                id=ids[idx],  # type: ignore[arg-type]
                classification=f"Hypothesis {ids[idx]}",
                headline="(not generated)",
                statement="",
                drawnFrom=[],
                falsifiablePrediction="",
            )
        )
    return out
